### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by skiano** [xpepermint/translatedjs#1]
I was looking around to see if anyone is trying to implement something close to https://github.com/yahoo/react-intl for vue, and this seems like the closest thing I have found.

But I was looking at the code and it seems like its not caching as proposed by https://github.com/yahoo/intl-format-cache. Are you caching in some other way?

**Comment by xpepermint** [comment]
Thanks for pointing this out. Caching, as proposed by the link, is not included at the moment. So far I haven't got any performance issues so I'm not sure if that's even needed. I try to keep things simple and as light as possible thus the package size stays at the minimum.

Using this library on the client side (browser) should be straight forward. Rather than using caching on this level you should use Vue's component based caching. The same applies to the server-side (SSR).

If you could share your use case in detail, maybe we can come up with something. For now I would say that Vue's built-in caching should do the trick.

**Comment by skiano** [comment]
Interesting. I didn't think about vue's caching. I'm trying a few things, and i'll definitely share what I have with you if it gets a little further to see what you think.

**Comment by xpepermint** [comment]
Feel free to reopen this issue at any time.
